// Throwaway: drive the pause -> photo mode flow and screenshot it.
import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), 'out');
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 }, acceptDownloads: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('pageerror', e.message));
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log(`[${m.type()}] ${m.text()}`); });
const wait = (fn, arg) => page.waitForFunction(fn, arg, { timeout: 300000, polling: 100 });
const ready = () => wait(() => window.__game?.menus?.screen && window.__game.menus._cooldown <= 0);
await page.goto('http://localhost:5411/?quick=bubblegum-bay&players=2&autodrive=1&cpus=5');
await wait(() => window.__game?.race?.state === 'racing' && window.__game.race.time > 2.5);
await page.keyboard.press('Escape');
await wait(() => window.__game?.menus?.screenId === 'pause');
await ready();
await page.screenshot({ path: path.join(OUT, 'photo-0-pause.png') });
const labels = await page.evaluate(() => [...document.querySelectorAll('.sk-pause .sk-listbtn')].map((b) => b.textContent));
console.log('pause options', labels);
const idx = labels.findIndex((t) => /Photo/.test(t));
for (let i = 0; i < idx; i++) { await page.keyboard.press('KeyS'); await page.waitForTimeout(150); }
await ready();
await page.keyboard.press('Enter');
await wait(() => window.__game?.menus?.screenId === 'photo-mode');
await ready();
const f0 = await page.evaluate(() => window.__game.frames);
await wait((f) => window.__game.frames > f + 3, f0);
await page.screenshot({ path: path.join(OUT, 'photo-1.png') });
for (const k of ['KeyD', 'KeyD', 'KeyD', 'KeyW']) { await page.keyboard.press(k); await page.waitForTimeout(250); }
await page.keyboard.press('Tab');
await page.waitForTimeout(300);
const f1 = await page.evaluate(() => window.__game.frames);
await wait((f) => window.__game.frames > f + 3, f1);
await page.screenshot({ path: path.join(OUT, 'photo-2.png') });
const dl = page.waitForEvent('download', { timeout: 60000 });
await page.keyboard.press('Enter');
const d = await dl;
await d.saveAs(path.join(OUT, 'photo-saved.png'));
console.log('downloaded', d.suggestedFilename(), JSON.stringify(await page.evaluate(() => window.__game.lastPhoto)));
await page.waitForTimeout(400);
await page.screenshot({ path: path.join(OUT, 'photo-3-toast.png') });
await page.keyboard.press('Escape');
await wait(() => window.__game?.menus?.screenId === 'pause');
await ready();
await page.keyboard.press('Escape');
await wait(() => window.__game?.state === 'race' && !window.__game.menus.screen);
console.log('back to racing', await page.evaluate(() => window.__game.race.state));
await browser.close();
