// Aurora Ice Palace: shimmering and graceful. Glass lead over sparkly bell
// arpeggios and warm strings, with a gentle echo like a frosty hall.
// OWNER: track builder (Superstar Cup). E major, twinkly, never sad.
export default {
  id: 'aurora-palace',
  bpm: 104,
  echo: 0.28,
  instruments: { lead: 'glass', counter: 'musicbox', arp: 'bell', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.5, counter: 0.14, arp: 0.13, pad: 0.16, bass: 0.36, drums: 0.3 },
  reverb: { lead: 0.5, counter: 0.4, arp: 0.45, pad: 0.5 },
  kit: {
    A: 'k . t . h . t . k . t k h . t .',
    B: 'k . t . h . t t k . t k h . o .',
    F: 'k . t . h . t . k . k . o . . .',
  },
  main: {
    bassStyle: 'soft',
    arpStyle: 'up16',
    padStyle: 'whole',
    chords: ['E', 'C#m7', 'Amaj7', 'B', 'E', 'G#m7', 'Amaj7', 'B', 'C#m7', 'Amaj7', 'E', 'B', 'Amaj7', 'B', 'E', 'B'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'G#5 - B5 - E6 - D#6 -',
      'C#6 - - - B5 - G#5 -',
      'A5 - C#6 - E6 - F#6 -',
      'D#6 - - - . . B5 .',
      'G#5 - B5 - E6 - G#6 -',
      'F#6 - D#6 - B5 - G#5 -',
      'A5 - C#6 - E6 - C#6 -',
      'B5 - - - - - . .',
      'C#6 - E6 - G#6 - E6 -',
      'C#6 - A5 - E5 - A5 -',
      'B5 - G#5 - E5 - G#5 -',
      'F#5 - - - D#5 - F#5 -',
      'A5 - B5 - C#6 - E6 -',
      'D#6 - C#6 - B5 - F#5 -',
      'G#5 - B5 - E6 - F#6 -',
      'G#6 - - - F#6 - D#6 -',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'B4 - - - - - - -',
      'D#5 - - - - - - -',
      'C#5 - - - - - - -',
      'D#5 - - - F#5 - - -',
      'E5 - - - - - - -',
      'C#5 - - - - - - -',
      'G#4 - - - - - - -',
      'B4 - - - - - - -',
      'C#5 - - - - - - -',
      'D#5 - - - - - - -',
      'E5 - - - G#5 - - -',
      'B4 - - - - - . .',
    ],
  },
};
