// Bubblegum Bay: sunny surf-pop in A major. A bouncy synth-whistle lead over
// ukulele off-beat strums, a bell answering like a bubble going "pop!", and a
// beachy tom groove. OWNER: Tracks — Bubble Cup.
export default {
  id: 'bubblegum-bay',
  bpm: 132,
  instruments: { lead: 'lead', counter: 'bell', arp: 'pluck', pad: 'pluck', bass: 'bass' },
  mix: { lead: 0.52, counter: 0.16, arp: 0.1, pad: 0.15, bass: 0.44, drums: 0.4 },
  reverb: { lead: 0.25, counter: 0.4, arp: 0.2, pad: 0.15 },
  kit: {
    A: 'k . h . s . h k k . h . s . h .',
    B: 'k . h . s . h . k k h . s . m m',
    F: 'k . m . s . m . k m m . s s s s',
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'updown8',
    padStyle: 'stabs',
    chords: ['A', 'F#m', 'D', 'E', 'A', 'F#m', 'Bm7', 'E', 'D', 'E', 'C#m', 'F#m', 'D', 'E', 'A', 'E7'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'E5 . A5 . C#6 - B5 A5',
      'F#5 - A5 - C#6 - A5 .',
      'F#5 . A5 . D6 - C#6 B5',
      'B5 - G#5 - E5 - . .',
      'E5 . A5 . C#6 - E6 -',
      'C#6 - A5 F#5 - . F#5 A5',
      'B5 - D6 - F#5 - A5 -',
      'G#5 - - - E5 . . .',
      'A5 . F#5 A5 D6 - . A5',
      'B5 . G#5 B5 E6 - . B5',
      'C#6 - B5 - G#5 - E5 -',
      'A5 - - - F#5 - . .',
      'F#5 A5 D6 - F#6 - D6 -',
      'E6 - D6 C#6 B5 - G#5 -',
      'A5 . C#6 . E6 - C#6 -',
      'A5 - - - . . E5 .',
    ],
    // little "pop!" answers from the bell at the end of phrases
    counter: [
      '. . . . . . . .',
      '. . . . . . E6 .',
      '. . . . . . . .',
      '. . . . . . B5 E6',
      '. . . . . . . .',
      '. . . . . . C#6 .',
      '. . . . . . . .',
      '. . . . B5 . E6 .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . C#6 . F#6 .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . E6 . A6 .',
    ],
  },
};
