// Cocoa Canyon: a happy trotting cowboy tune. Whistled melody, clip-clop toms
// and shakers, strummy plucks and a friendly brass harmony. D major, swung.
export default {
  id: 'cocoa-canyon',
  bpm: 116,
  swing: 0.28,
  instruments: { lead: 'whistle', counter: 'brass', arp: 'pluck', pad: 'pluck', bass: 'bass' },
  mix: { lead: 0.44, counter: 0.14, arp: 0.1, pad: 0.16, bass: 0.44, drums: 0.4 },
  reverb: { lead: 0.3, counter: 0.25, pad: 0.15 },
  kit: {
    A: 'k . t . m . t . k . t . m . t t',
    B: 'k . t . m . t t k . t . m . s .',
    F: 'k . m . m . s . m m s . s s s s',
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'none',
    padStyle: 'stabs',
    chords: ['D', 'Bm', 'G', 'A', 'D', 'Bm', 'Em7', 'A7', 'G', 'A', 'F#m', 'Bm', 'G', 'A7', 'D', 'D'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'A4 . D5 . F#5 - E5 D5',
      'F#5 - B5 . A5 - F#5 .',
      'G5 . B5 . D6 - B5 G5',
      'A5 - - - E5 . C#5 .',
      'D5 . F#5 A5 - F#5 A5 .',
      'B5 - A5 F#5 D5 - B4 .',
      'E5 . G5 B5 - A5 G5 E5',
      'C#5 - E5 - A5 - . .',
      'B5 . B5 A5 G5 . D5 .',
      'C#6 . C#6 B5 A5 . E5 .',
      'F#5 - A5 - C#6 - A5 F#5',
      'B5 - - - F#5 - D5 .',
      'G5 . B5 D6 - B5 G5 .',
      'A5 . C#6 E6 - C#6 A5 G5',
      'F#5 - A5 - D6 - A5 F#5',
      'D5 - - - . . . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'F#4 - - - A4 - - -',
      'D4 - - - F#4 - - -',
      'G4 - - - B4 - - -',
      'A4 - - - C#5 - - -',
      'D5 - - - B4 - - -',
      'E5 - - - C#5 - - -',
      'C#5 - - - A4 - - -',
      'D5 - - - B4 - - -',
      'B4 - - - D5 - - -',
      'C#5 - - - E5 - - -',
      'D5 - - - A4 - - -',
      'F#4 - - - - - . .',
    ],
  },
};
