// Jellybean Jungle: bouncy marimba-style plucks over bongo toms, a jungle
// whistle joining in for the second half. F major, skippy and sunny.
export default {
  id: 'jellybean-jungle',
  bpm: 128,
  instruments: { lead: 'pluck', counter: 'whistle', arp: 'musicbox', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.62, counter: 0.2, arp: 0.12, pad: 0.1, bass: 0.42, drums: 0.4 },
  reverb: { lead: 0.25, counter: 0.3, arp: 0.3, pad: 0.35 },
  kit: {
    A: 'k . t m s . t . k k t m s . m m',
    B: 'k . t . s . t m k . t . s m m .',
    F: 'k . m . m . s . m m m . s s s s',
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'musicbox',
    padStyle: 'whole',
    chords: ['F', 'Dm', 'Bb', 'C', 'F', 'Dm', 'Gm7', 'C7', 'Bb', 'C', 'Am', 'Dm', 'Bb', 'C', 'F', 'F'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'F5 . A5 C6 - A5 F5 .',
      'D5 - F5 . A5 - G5 F5',
      'D5 . F5 Bb5 - A5 G5 .',
      'G5 - - . C5 D5 E5 G5',
      'F5 . A5 C6 - D6 C6 A5',
      'A5 - F5 . D5 - F5 A5',
      'G5 . Bb5 D6 - C6 Bb5 G5',
      'E5 - - - C5 . . .',
      'D6 . D6 C6 Bb5 . A5 G5',
      'C6 - G5 . E5 . G5 C6',
      'C6 . A5 E5 - C5 E5 A5',
      'F5 - A5 . D6 - C6 A5',
      'Bb5 - D6 - F6 - D6 Bb5',
      'C6 - E6 - G6 - E6 C6',
      'F6 - C6 A5 F5 - C5 .',
      'F5 - - - . . . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'F5 - - - - - - -',
      'E5 - - - - - - -',
      'E5 - - - - - - -',
      'F5 - - - - - - -',
      'D5 - - - - - - -',
      'E5 - - - - - - -',
      'F5 - - - A5 - - -',
      'F5 - - - - - . .',
    ],
  },
};
