// Mermaid Lagoon: a dreamy, shimmery swim in E-flat major. Music-box melody
// floating over glassy long notes, rippling bell arpeggios and a soft,
// bubbling shaker groove. OWNER: Tracks — Bubble Cup.
export default {
  id: 'mermaid-lagoon',
  bpm: 100,
  echo: 0.28,
  instruments: { lead: 'musicbox', counter: 'glass', arp: 'bell', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.55, counter: 0.18, arp: 0.11, pad: 0.16, bass: 0.36, drums: 0.28 },
  reverb: { lead: 0.5, counter: 0.55, arp: 0.45, pad: 0.5 },
  kit: {
    A: 'k . . t c . . t k . t . c . t t',
    F: 'k . t . c . t . k . m . m . o .',
  },
  main: {
    bassStyle: 'soft',
    arpStyle: 'updown8',
    padStyle: 'whole',
    chords: ['Ebmaj7', 'Cm7', 'Abmaj7', 'Bb', 'Ebmaj7', 'Gm7', 'Abmaj7', 'Bb7', 'Cm7', 'Abmaj7', 'Fm7', 'Bb', 'Ebmaj7', 'Abmaj7', 'Fm7', 'Bb7'],
    drums: 'AAAAAAAF AAAAAAAF',
    lead: [
      'G5 - - - Bb5 - D6 -',
      'Eb6 - - - C6 - Bb5 -',
      'C6 - - - Eb6 - G6 -',
      'F6 - - - - - . .',
      'G5 - Bb5 - Eb6 - D6 -',
      'D6 - Bb5 - G5 - F5 -',
      'Ab5 - C6 - Eb6 - G6 -',
      'F6 - D6 - Bb5 - Ab5 -',
      'G5 - - - Eb5 - G5 -',
      'C6 - - - Bb5 - G5 -',
      'Ab5 - C6 - Eb6 - F6 -',
      'D6 - - - - - Bb5 -',
      'Eb6 - G6 - F6 - Eb6 -',
      'C6 - - - Eb6 - C6 -',
      'Ab5 - Bb5 - C6 - Eb6 -',
      'D6 - - - F6 - - -',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'Bb4 - - - - - - -',
      'Bb4 - - - D5 - - -',
      'C5 - - - - - - -',
      'D5 - - - - - - -',
      'Eb5 - - - - - - -',
      'C5 - - - - - - -',
      'Ab4 - - - C5 - - -',
      'F5 - - - D5 - - -',
      'G5 - - - - - - -',
      'Eb5 - - - - - - -',
      'C5 - - - Ab4 - - -',
      'F4 - - - - - . .',
    ],
  },
};
