// Moonbounce Base: a boing-boing space groove. Vibes lead that hops in
// octaves, a pulsing bass, echoing bell sparkles and toms like moon-boots.
// OWNER: track builder (Superstar Cup). G major, bouncy and silly.
export default {
  id: 'moonbounce-base',
  bpm: 118,
  echo: 0.25,
  instruments: { lead: 'vibes', counter: 'glass', arp: 'bell', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.52, counter: 0.14, arp: 0.12, pad: 0.13, bass: 0.44, drums: 0.38 },
  reverb: { lead: 0.35, counter: 0.45, arp: 0.45, pad: 0.4 },
  kit: {
    A: 'k . h . s . h m k . h . s . m .',
    B: 'k . h k s . h . k . h m s . m m',
    F: 'k . m . s . m . k . m m s s s s',
  },
  main: {
    bassStyle: 'pulse',
    arpStyle: 'updown8',
    padStyle: 'whole',
    chords: ['G', 'Em7', 'C', 'D', 'G', 'Em7', 'Am7', 'D', 'C', 'D', 'Bm7', 'Em7', 'C', 'D', 'G', 'D'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'G4 . G5 . D5 . B4 .',
      'E5 . E6 . B5 . G5 .',
      'C5 . C6 . G5 . E5 .',
      'D5 - F#5 - A5 - . .',
      'G4 . G5 . D5 . B4 .',
      'E5 . E6 . B5 . G5 .',
      'A5 . C6 . E6 . C6 .',
      'D6 - - - A5 - F#5 -',
      'E5 - G5 - C6 - B5 -',
      'A5 - F#5 - D5 - F#5 -',
      'B5 - D6 - F#6 - D6 -',
      'G5 - - - E5 - . .',
      'E5 . G5 . C6 . E6 .',
      'D6 . C6 . A5 . F#5 .',
      'G5 - B5 - D6 - G6 -',
      'F#6 - - - D6 - A5 -',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'G5 - - - E5 - - -',
      'F#5 - - - A5 - - -',
      'D5 - - - F#5 - - -',
      'B4 - - - E5 - - -',
      'G5 - - - - - - -',
      'A5 - - - - - - -',
      'B5 - - - D6 - - -',
      'A5 - - - - - . .',
    ],
  },
};
