// Peppermint Village: a jingly sleigh-ride gallop. Sparkly bell melody,
// sleigh-bell shakers on every eighth, a bouncy bass and brassy fills. D major.
// OWNER: Tracks — Cozy Cup.
export default {
  id: 'peppermint-village',
  bpm: 140,
  instruments: { lead: 'bell', counter: 'brass', arp: 'musicbox', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.56, counter: 0.16, arp: 0.13, pad: 0.12, bass: 0.42, drums: 0.4 },
  reverb: { lead: 0.35, counter: 0.25, arp: 0.35, pad: 0.4 },
  kit: {
    A: 'kt . t . st . t . kt . t k st . t .',
    B: 'kt . t . st . t . kt . t k st . o t',
    F: 'kt . t . st . t . m . m . s s s s',
  },
  intro: {
    bassStyle: 'soft',
    arpStyle: 'musicbox',
    padStyle: 'whole',
    chords: ['D', 'A7'],
    drums: 'AF',
    lead: [
      'A5 . A5 . A5 - - .',
      'E5 . F#5 . G5 - A5 .',
    ],
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'musicbox',
    padStyle: 'whole',
    chords: ['D', 'G', 'A', 'D', 'Bm', 'G', 'E7', 'A', 'D', 'G', 'A', 'Bm', 'G', 'A7', 'D', 'D'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'F#5 F#5 F#5 - A5 - F#5 -',
      'G5 - B5 - D6 - B5 -',
      'A5 - C#6 - E6 - C#6 A5',
      'F#5 - - - D5 . E5 .',
      'F#5 . B5 . D6 - B5 .',
      'G5 . B5 . D6 - E6 D6',
      'B5 - G#5 - E5 - D6 -',
      'C#6 - - - A5 . . .',
      'D6 - A5 - F#5 - A5 -',
      'B5 - G5 - D5 - G5 B5',
      'A5 - E5 - C#5 - E5 A5',
      'B5 - - - F#5 - D5 -',
      'G5 A5 B5 - D6 - B5 -',
      'A5 B5 C#6 - E6 - C#6 -',
      'D6 . A5 . F#5 . A5 .',
      'D6 - - - . . . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . A4 . C#5 .',
      'D5 - - - . . . .',
      'B4 - - - . . . .',
      'G#4 - - - B4 - - -',
      'A4 - - - E5 . C#5 .',
      'A4 - - - . . . .',
      'B4 - - - . . . .',
      'C#5 - - - . . . .',
      'D5 - - - B4 - - -',
      'B4 - - - D5 - - -',
      'C#5 - - - E5 - - -',
      'F#5 - - - A4 - - -',
      'D5 - - - . . . .',
    ],
  },
};
