// Pillow Fort Dreamland: a floaty lullaby that still loves to zoom. Glassy
// melody with dreamy echoes over twinkly sparkle arps and soft strings,
// a heartbeat kick and gentle shakers. Eb major.
// OWNER: Tracks — Cozy Cup.
export default {
  id: 'pillow-fort',
  bpm: 100,
  echo: 0.3,
  instruments: { lead: 'glass', counter: 'musicbox', arp: 'bell', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.52, counter: 0.14, arp: 0.12, pad: 0.17, bass: 0.36, drums: 0.28 },
  reverb: { lead: 0.55, counter: 0.5, arp: 0.5, pad: 0.5 },
  kit: {
    A: 'k . t . h . t . k k t . h . t .',
    F: 'k . t . h . t . k . k . o . . .',
  },
  main: {
    bassStyle: 'soft',
    arpStyle: 'updown8',
    padStyle: 'whole',
    chords: ['Eb', 'Cm', 'Ab', 'Bb', 'Eb', 'Gm', 'Ab', 'Bb', 'Cm', 'Ab', 'Fm', 'Bb', 'Eb', 'Ab', 'Fm', 'Bb'],
    drums: 'AAAAAAAF AAAAAAAF',
    lead: [
      'G5 - Bb5 - Eb6 - - -',
      'Eb6 - D6 - C6 - G5 -',
      'Ab5 - C6 - Eb6 - C6 -',
      'Bb5 - - - F5 - - -',
      'G5 - Bb5 - Eb6 - F6 -',
      'G6 - F6 - D6 - Bb5 -',
      'C6 - Ab5 - Eb5 - F5 -',
      'D5 - F5 - Bb5 - - -',
      'C6 - - - G5 - Eb5 -',
      'Ab5 - - - C6 - Eb6 -',
      'F5 - Ab5 - C6 - Ab5 -',
      'Bb5 - - - D6 - - -',
      'Eb6 - D6 - Bb5 - G5 -',
      'C6 - Eb6 - Ab5 - C6 -',
      'F5 - G5 - Ab5 - C6 -',
      'Bb5 - - - - - . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . D6 . F6 .',
      'Eb6 . . . . . . .',
      'D6 . . . . . . .',
      'C6 . . . . . . .',
      'Bb5 . . . . . . .',
      '. . Eb6 . . . G6 .',
      '. . Eb6 . . . C6 .',
      '. . F6 . . . Ab6 .',
      '. . F6 . . . D6 .',
      '. . G6 . . . Eb6 .',
      '. . Ab6 . . . Eb6 .',
      '. . C6 . . . F6 .',
      'D6 - - - . . . .',
    ],
  },
};
