// Pumpkin Pie Patch: a skippy barn-dance hoedown. Whistle fiddle-tune over
// banjo-ish plucks, a bouncy bass and a clip-clop shaker. G major.
// OWNER: Tracks — Cozy Cup.
export default {
  id: 'pumpkin-patch',
  bpm: 132,
  instruments: { lead: 'whistle', counter: 'pluck', arp: 'pluck', pad: 'pluck', bass: 'bass' },
  mix: { lead: 0.44, counter: 0.14, arp: 0.1, pad: 0.15, bass: 0.44, drums: 0.4 },
  reverb: { lead: 0.22, counter: 0.2, arp: 0.18, pad: 0.15 },
  kit: {
    A: 'k . t . s . t t k k t . s . t .',
    B: 'k . t . s . t t k . t k s . c c',
    F: 'k . t . s . t . k . s . s s m m',
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'updown8',
    padStyle: 'stabs',
    chords: ['G', 'C', 'G', 'D', 'G', 'C', 'D', 'G', 'Em', 'C', 'G', 'D', 'C', 'D', 'G', 'G'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'D5 . G5 G5 B5 . G5 .',
      'E5 . G5 . C6 - B5 A5',
      'G5 . B5 . D6 - B5 G5',
      'A5 - - - F#5 . D5 .',
      'D5 . G5 G5 B5 . G5 .',
      'E5 . G5 . C6 - E6 D6',
      'C6 B5 A5 G5 F#5 - A5 .',
      'G5 - - - . . D5 E5',
      'G5 . E5 . B5 - A5 G5',
      'E5 . C5 . E5 G5 C6 .',
      'B5 . G5 . D5 G5 B5 .',
      'A5 - F#5 - D5 - . .',
      'E6 - D6 C6 G5 - C6 -',
      'D6 - C6 B5 A5 - F#5 -',
      'G5 . B5 . D6 . B5 .',
      'G5 - - - . . . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . D4 . F#4 .',
      'B4 . . . D5 . . .',
      'C5 . . . E5 . . .',
      'D5 . . . C5 . . .',
      'B4 . . . . . . .',
      'E4 . G4 . B4 . G4 .',
      'C5 . G4 . E4 . G4 .',
      'D4 . G4 . B4 . G4 .',
      'F#4 . A4 . D5 . . .',
      'G4 . C5 . E5 . C5 .',
      'A4 . D5 . F#5 . D5 .',
      'B4 . D5 . G5 . D5 .',
      'G4 - - - . . . .',
    ],
  },
};
