// Ribbon Sky Rally: the grand finale. A brassy fanfare intro, then a soaring
// bell melody over rolling up16 arpeggios, strings and a big happy backbeat.
// OWNER: track builder (Superstar Cup). D major, triumphant and joyful.
export default {
  id: 'ribbon-sky',
  bpm: 138,
  instruments: { lead: 'bell', counter: 'whistle', arp: 'pluck', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.56, counter: 0.15, arp: 0.14, pad: 0.15, bass: 0.44, drums: 0.42 },
  reverb: { lead: 0.35, counter: 0.3, arp: 0.25, pad: 0.4 },
  kit: {
    V: 'k . . . s . . . k . k . s s s s',
    A: 'k . h . s . h . k . h k s . h .',
    B: 'k . h . s . h t k k h . s . h o',
    F: 'k . h . s . h . m . m . s s s s',
  },
  intro: {
    instruments: { lead: 'brass' },
    mix: { lead: 0.42 },
    bassStyle: 'soft',
    arpStyle: 'none',
    padStyle: 'whole',
    chords: ['D', 'G', 'A', 'D'],
    drums: 'VVVV',
    lead: [
      'A4 A4 D5 - F#5 - A5 -',
      'B5 - A5 G5 B5 - - -',
      'A5 - E5 - C#6 - B5 A5',
      'D6 - - - - - . .',
    ],
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'up16',
    padStyle: 'whole',
    chords: ['D', 'A', 'Bm', 'G', 'D', 'A', 'G', 'A', 'Bm', 'G', 'D', 'A', 'G', 'A', 'D', 'D'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'F#5 - A5 - D6 - C#6 D6',
      'E6 - C#6 - A5 - . A5',
      'B5 - D6 - F#6 - E6 D6',
      'D6 - B5 - G5 - . .',
      'F#5 - A5 - D6 - E6 F#6',
      'E6 - C#6 - A5 - C#6 E6',
      'D6 - B5 - G5 - B5 D6',
      'C#6 - - - E6 - . .',
      'F#6 - E6 - D6 - B5 -',
      'D6 - B5 - G5 - B5 -',
      'A5 - F#5 - D6 - F#6 -',
      'E6 - - - C#6 - A5 -',
      'B5 - D6 - G6 - F#6 -',
      'E6 - F#6 - E6 - C#6 -',
      'D6 - - - F#6 - A6 -',
      'F#6 - - - D6 - . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'A4 - - - D5 - - -',
      'C#5 - - - E5 - - -',
      'B4 - - - D5 - - -',
      'E5 - - - - - - -',
      'D5 - - - F#5 - - -',
      'B4 - - - D5 - - -',
      'A4 - - - F#5 - - -',
      'C#5 - - - E5 - - -',
      'D5 - - - B4 - - -',
      'C#5 - - - A4 - - -',
      'F#5 - - - A5 - - -',
      'A5 - - - - - . .',
    ],
  },
};
