// Sprinkle Kart title theme: a sunny, bouncy "here we go!" tune for the title
// show. Bell lead with a whistle answer, music-box sparkles, bouncy bass and a
// little fanfare intro. OWNER: showcase presentation. G major, happy and hummable.
export default {
  id: 'skx-title',
  bpm: 126,
  instruments: { lead: 'bell', counter: 'whistle', arp: 'musicbox', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.55, counter: 0.16, arp: 0.13, pad: 0.12, bass: 0.42, drums: 0.38 },
  reverb: { lead: 0.35, counter: 0.3, arp: 0.35, pad: 0.35 },
  kit: {
    A: 'k . h . s . h . k . h k s . h .',
    B: 'k . h . s . h t k . h k s . h h',
    F: 'k . h . s . h . m . m . s s s s',
    I: 'k . . . . . . . k . . . s s s s',
  },
  intro: {
    bassStyle: 'soft',
    arpStyle: 'musicbox',
    padStyle: 'whole',
    chords: ['G', 'D'],
    drums: 'II',
    lead: [
      'G5 . G5 . B5 - D6 -',
      'D6 - C6 - B5 - A5 -',
    ],
  },
  main: {
    bassStyle: 'bounce',
    arpStyle: 'up16',
    padStyle: 'whole',
    chords: ['G', 'Em', 'C', 'D', 'G', 'Em', 'Am7', 'D7', 'C', 'D', 'Bm', 'Em', 'C', 'Am7', 'D7', 'G'],
    drums: 'ABABABAF ABABABAF',
    lead: [
      'D5 . G5 . B5 - A5 G5',
      'E5 - G5 - B5 - - .',
      'C6 . B5 . A5 - G5 E5',
      'F#5 - - - D5 . . .',
      'D5 . G5 . B5 - D6 -',
      'E6 - D6 B5 - . G5 A5',
      'C6 - B5 - A5 - E5 F#5',
      'A5 - - - F#5 - D5 -',
      'E5 - G5 - C6 - E6 -',
      'D6 - C6 - A5 - F#5 -',
      'D6 - B5 - F#5 - B5 D6',
      'E6 - - - B5 - G5 -',
      'E5 - G5 - C6 - B5 A5',
      'C6 - E6 - A5 - C6 -',
      'B5 - A5 - F#5 - A5 -',
      'G5 - - - . . D5 .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . D6 . . .',
      '. . . . . . . .',
      '. . . . A5 . D6 .',
      '. . . . . . . .',
      '. . . . . . B5 .',
      '. . . . . . . .',
      '. . . . D6 . . .',
      'G5 . . . E5 . . .',
      'A5 . . . D5 . . .',
      'F#5 . . . D5 . . .',
      'G5 . . . E5 . . .',
      'C6 . . . G5 . . .',
      'E5 . . . A5 . . .',
      'D6 . . . C6 . . .',
      'B5 . D6 . G6 . . .',
    ],
  },
};
