// Teacup Garden: a dainty, twirly tea-party minuet. Bell melody over rippling
// music-box arpeggios and soft strings, with a polite little clap. F major.
// OWNER: Tracks — Cozy Cup.
export default {
  id: 'teacup-garden',
  bpm: 116,
  instruments: { lead: 'bell', counter: 'glass', arp: 'musicbox', pad: 'pad', bass: 'bass' },
  mix: { lead: 0.56, counter: 0.12, arp: 0.14, pad: 0.13, bass: 0.38, drums: 0.3 },
  reverb: { lead: 0.4, counter: 0.45, arp: 0.35, pad: 0.4 },
  kit: {
    A: 'k . . t c . t . k . t . c . t t',
    F: 'k . . t c . t . k . c . c c c .',
  },
  main: {
    bassStyle: 'soft',
    arpStyle: 'up16',
    padStyle: 'whole',
    chords: ['F', 'Bb', 'C', 'F', 'Dm', 'Gm', 'C', 'F', 'Bb', 'C', 'Am', 'Dm', 'Gm', 'C', 'F', 'F'],
    drums: 'AAAAAAAF AAAAAAAF',
    lead: [
      'A5 - C6 - F6 - E6 D6',
      'D6 - Bb5 - F5 - G5 A5',
      'G5 - E5 - C5 - E5 G5',
      'F5 - - - A5 - C6 -',
      'D6 - F6 - D6 - A5 -',
      'Bb5 - D6 - G5 - A5 Bb5',
      'C6 - E6 - G5 - Bb5 -',
      'A5 - - - . . C5 .',
      'D5 F5 Bb5 - D6 - C6 Bb5',
      'C6 - G5 - E5 - G5 -',
      'A5 - C6 - E6 - C6 -',
      'D6 - A5 - F5 - A5 -',
      'Bb5 - A5 G5 D5 - G5 -',
      'E5 - G5 - C6 - E6 -',
      'F6 - C6 - A5 - C6 -',
      'F5 - - - - - . .',
    ],
    counter: [
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      '. . . . . . . .',
      'F5 - - - A5 - - -',
      'D5 - - - G5 - - -',
      'E5 - - - G5 - - -',
      'F5 - - - C5 - - -',
      'F5 - - - D5 - - -',
      'E5 - - - C5 - - -',
      'E5 - - - A5 - - -',
      'F5 - - - D5 - - -',
      'D5 - - - Bb4 - - -',
      'C5 - - - G5 - - -',
      'A5 - - - F5 - - -',
      'C5 - - - - - . .',
    ],
  },
};
