import { chromium } from 'playwright';
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await (await browser.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
p.on('pageerror', (e) => console.log('ERR', e.message));
const press = async (k, ms = 800) => { await p.keyboard.press(k); await p.waitForTimeout(ms); };
await p.goto('http://localhost:5281/?quick=gumdrop-meadow&players=2&autodrive=1&simspeed=8&speed=zoomy&cpus=0&unlockreset=1');
await p.waitForFunction(() => window.__game?.state === 'results', null, { timeout: 240000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: 'dev/feat/modes-timing/r0-results.png' });
await p.goto('http://localhost:5281/');
await p.waitForFunction(() => window.__game?.state === 'menu' && document.querySelector('.sk-menus:not([hidden])'), null, { timeout: 60000 });
await p.waitForTimeout(800);
await press('Enter', 900);
await press('Enter', 1000);
await press('KeyS', 500);
await press('Enter', 1200);
await p.screenshot({ path: 'dev/feat/modes-timing/r1-records.png' });
console.log(await p.evaluate(() => localStorage.getItem('sprinkle-kart-record-holders-v1')));
await browser.close();
