const TWIRL = { turn: 360, r: 1e-6 };
export default {
  jungle: {
    width: 18,
    spec: {
      start: [0, 0], heading: 45, startAt: 72,
      ops: [
        { s: 90, y: 0, flex: true, mark: 'under-bridge' },
        { turn: 100, r: 80, y: 2, mark: 'b1' },
        { s: 50, y: 4, mark: 'b2' },
        { turn: 80, r: 70, y: 6, mark: 'b3' },
        { s: 40, y: 8, mark: 'b4' },
        { turn: 90, r: 85, y: 10, mark: 'b5' },
        { s: 90, y: 10, mark: 'bridge-in' },
        TWIRL,
        { s: 70, y: 10, flex: true, mark: 'bridge-out' },
        { turn: -90, r: 55, y: 8, mark: 'a1' },
        { s: 60, y: 5, mark: 'a2' },
        { turn: -90, r: 40, y: 3, mark: 'a3' },
        { s: 40, y: 1, mark: 'a4' },
        { turn: -90, r: 60, y: 0, mark: 'a5' },
        { s: 80, y: 0, mark: 'home' },
      ],
    },
  },
  canyon: {
    width: 18,
    spec: {
      start: [0, 0], heading: 0, startAt: 54,
      ops: [
        { s: 120, flex: true, mark: 'start-straight' },
        { turn: -40, r: 90, mark: 'esses-1' },
        { turn: 60, r: 80, y: 2, mark: 'esses-2' },
        { turn: -50, r: 90, y: 4, mark: 'esses-3' },
        { s: 80, y: 6, mark: 'slot-canyon' },
        { turn: -150, r: 105, y: 11, mark: 'sweeper' },
        { s: 110, y: 11, mark: 'mesa-top' },
        { turn: -60, r: 60, y: 9, mark: 'mesa-exit' },
        { s: 50, y: 7, flex: true, mark: 'descent' },
        { s: 36, y: 6, mark: 'bridge' },
        { s: 50, y: 4, mark: 'descent-2' },
        { turn: 60, r: 60, y: 3, mark: 'finger-turn' },
        { s: 90, y: 2, mark: 'finger-run' },
        { turn: -180, r: 30, y: 1, mark: 'hairpin' },
        { s: 30, y: 0, mark: 'return' },
        { turn: 20, r: 80, mark: 'kink' },
        { turn: -20, r: 80, mark: 'kink2' },
      ],
    },
  },
  volcano: {
    width: 20,
    spec: {
      start: [0, 0], heading: 0, startAt: 54,
      ops: [
        { s: 110, flex: true, mark: 'start-straight' },
        { turn: 70, r: 100, y: 2, mark: 'beach-bend' },
        { s: 60, y: 5, mark: 'climb' },
        { turn: 80, r: 130, y: 11, mark: 'fizz-ridge' },
        { s: 40, y: 13, hump: 1, mark: 'lemon-bridge' },
        { turn: 60, r: 120, y: 14, mark: 'summit-sweep' },
        { turn: -70, r: 60, y: 12, mark: 'rim-s1' },
        { turn: 110, r: 50, y: 9, mark: 'rim-s2' },
        { s: 80, flex: true, y: 4, mark: 'fizzy-descent' },
        { turn: 90, r: 70, y: 1, mark: 'shore-turn' },
        { s: 60, y: 0, mark: 'boardwalk' },
        { turn: 20, r: 80, y: 0, mark: 'last-turn' },
      ],
    },
  },
  downtown: {
    width: 18,
    spec: {
      start: [0, 0], heading: 0, startAt: 54,
      ops: [
        { s: 160, flex: true, mark: 'main-street' },
        { turn: -90, r: 38, mark: 'corner-1' },
        { s: 60, flex: true, mark: 'bakery-row' },
        { turn: 35, r: 50, mark: 'chicane-1' },
        { turn: -35, r: 50, mark: 'chicane-2' },
        { s: 30, mark: 'bakery-row-2' },
        { turn: -90, r: 36, mark: 'corner-2' },
        { s: 50, y: 6, mark: 'ramp-up' },
        { s: 50, y: 6, mark: 'overpass' },
        { s: 50, y: 0, mark: 'ramp-down' },
        { turn: 90, r: 36, mark: 'corner-3' },
        { s: 40, mark: 'sprinkle-st' },
        { turn: -90, r: 36, mark: 'corner-4' },
        { s: 80, mark: 'glaze-ave' },
        { turn: -90, r: 40, mark: 'corner-5' },
        { s: 250, mark: 'donut-avenue' },
        { turn: -90, r: 40, mark: 'corner-6' },
      ],
    },
  },
};
